[33mWARNING[0m:  [26-09-2024 18:27:24] chroma_server_nofile is not supported on Windows. chroma_server_nofile will not be set.
[32mINFO[0m:     [26-09-2024 18:27:24] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component System
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component SqliteDB
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component QuotaEnforcer
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component Posthog
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component LocalSegmentManager
[36mDEBUG[0m:    [26-09-2024 18:27:24] Starting component SegmentAPI
[32mINFO[0m:     [26-09-2024 18:27:24] Started server process [[36m18792[0m]
[32mINFO[0m:     [26-09-2024 18:27:24] Waiting for application startup.
[32mINFO[0m:     [26-09-2024 18:27:24] Application startup complete.
[32mINFO[0m:     [26-09-2024 18:27:24] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [26-09-2024 18:27:32] 127.0.0.1:58094 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:27:32] 127.0.0.1:58096 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [26-09-2024 18:27:32] Collection paper_knowledgebase already exists
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\streams\memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\streams\memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 98, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 185, in __call__
    with collapse_excgroups():
  File "C:\Users\Admin\anaconda3\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_utils.py", line 83, in collapse_excgroups
    raise exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 112, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 640, in create_collection
    await to_thread.run_sync(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 629, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\api\segment.py", line 178, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\db\mixins\sysdb.py", line 227, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection paper_knowledgebase already exists
[32mINFO[0m:     [26-09-2024 18:27:32] 127.0.0.1:58098 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [26-09-2024 18:31:05] 127.0.0.1:58189 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:31:05] 127.0.0.1:58191 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [26-09-2024 18:31:05] Collection paper_knowledgebase already exists
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\streams\memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\streams\memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 98, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 185, in __call__
    with collapse_excgroups():
  File "C:\Users\Admin\anaconda3\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_utils.py", line 83, in collapse_excgroups
    raise exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 112, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 640, in create_collection
    await to_thread.run_sync(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\server\fastapi\__init__.py", line 629, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\api\segment.py", line 178, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\chromadb\db\mixins\sysdb.py", line 227, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection paper_knowledgebase already exists
[32mINFO[0m:     [26-09-2024 18:31:05] 127.0.0.1:58193 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [26-09-2024 18:33:02] 127.0.0.1:58242 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:33:02] 127.0.0.1:58244 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:33:02] 127.0.0.1:58246 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:33:06] 127.0.0.1:58277 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 18:33:06] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [26-09-2024 18:33:06] 127.0.0.1:58279 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[33mWARNING[0m:  [26-09-2024 18:33:06] Number of requested results 5 is greater than number of elements in index 2, updating n_results = 2
[32mINFO[0m:     [26-09-2024 18:33:06] 127.0.0.1:58281 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:33:06] 127.0.0.1:58283 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[33mWARNING[0m:  [26-09-2024 18:33:07] Number of requested results 5 is greater than number of elements in index 4, updating n_results = 4
[32mINFO[0m:     [26-09-2024 18:33:07] 127.0.0.1:58285 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[33mWARNING[0m:  [26-09-2024 18:33:07] Number of requested results 5 is greater than number of elements in index 4, updating n_results = 4
[32mINFO[0m:     [26-09-2024 18:33:07] 127.0.0.1:58287 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:38:43] 127.0.0.1:58558 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:38:43] 127.0.0.1:58560 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 18:38:43] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 18:38:43] 127.0.0.1:58562 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:38:48] 127.0.0.1:58591 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:38:48] 127.0.0.1:58593 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 500
[32mINFO[0m:     [26-09-2024 18:38:48] 127.0.0.1:58595 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 400
[32mINFO[0m:     [26-09-2024 18:40:35] 127.0.0.1:58684 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:40:35] 127.0.0.1:58686 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 18:40:35] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 18:40:35] 127.0.0.1:58688 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:40:38] 127.0.0.1:58726 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:40:38] 127.0.0.1:58728 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[32mINFO[0m:     [26-09-2024 18:40:39] 127.0.0.1:58730 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:40:39] 127.0.0.1:58732 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[32mINFO[0m:     [26-09-2024 18:40:39] 127.0.0.1:58734 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:40:40] 127.0.0.1:58736 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:44:16] 127.0.0.1:58814 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:44:16] 127.0.0.1:58816 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 18:44:16] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 18:44:16] 127.0.0.1:58818 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:44:20] 127.0.0.1:58851 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:44:20] 127.0.0.1:58853 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[32mINFO[0m:     [26-09-2024 18:44:20] 127.0.0.1:58855 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:44:21] 127.0.0.1:58857 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[32mINFO[0m:     [26-09-2024 18:44:21] 127.0.0.1:58859 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:44:22] 127.0.0.1:58861 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:46:40] 127.0.0.1:58915 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:46:40] 127.0.0.1:58917 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 18:46:40] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 18:46:40] 127.0.0.1:58919 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:46:43] 127.0.0.1:58950 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:46:43] 127.0.0.1:58952 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[32mINFO[0m:     [26-09-2024 18:46:44] 127.0.0.1:58954 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:46:44] 127.0.0.1:58956 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/add HTTP/1.1" 201
[32mINFO[0m:     [26-09-2024 18:46:44] 127.0.0.1:58958 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 18:46:45] 127.0.0.1:58960 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:02:51] 127.0.0.1:59967 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:02:51] 127.0.0.1:59969 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:02:51] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:02:51] 127.0.0.1:59971 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:07:23] 127.0.0.1:60424 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:07:23] 127.0.0.1:60426 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:07:23] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:07:23] 127.0.0.1:60428 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:15:02] 127.0.0.1:60718 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:15:02] 127.0.0.1:60720 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:15:02] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:15:02] 127.0.0.1:60722 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:17:57] 127.0.0.1:60979 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:17:57] 127.0.0.1:60981 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:17:57] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:17:57] 127.0.0.1:60983 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:21:19] 127.0.0.1:61119 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:21:19] 127.0.0.1:61121 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:21:19] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:21:19] 127.0.0.1:61123 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:25:06] 127.0.0.1:61279 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:25:06] 127.0.0.1:61281 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:25:06] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:25:06] 127.0.0.1:61283 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:28:05] 127.0.0.1:61405 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:28:05] 127.0.0.1:61407 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:28:05] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:28:05] 127.0.0.1:61409 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:31:32] 127.0.0.1:61515 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:31:32] 127.0.0.1:61517 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:31:32] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:31:32] 127.0.0.1:61519 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:31:37] 127.0.0.1:61572 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:31:39] 127.0.0.1:61584 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:31:41] 127.0.0.1:61590 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:32:10] 127.0.0.1:61602 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:32:10] 127.0.0.1:61604 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [26-09-2024 19:32:10] Collection paper_knowledgebase_V1 already exists, returning existing collection.
[32mINFO[0m:     [26-09-2024 19:32:10] 127.0.0.1:61606 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:32:15] 127.0.0.1:61642 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:32:17] 127.0.0.1:61656 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
[32mINFO[0m:     [26-09-2024 19:32:19] 127.0.0.1:61662 - "POST /api/v1/collections/ea428610-4528-4c8b-9a0a-b23918f164fa/query HTTP/1.1" 200
